name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  # this step will dump the context from the issues created in gitlab and which are
  # open into the output as we are running an echo command on line 14.
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      # using a community action to add a comment on the issue
      # https://github.com/marketplace/actions/create-or-update-comment
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: "+1"
